""""added theme to be persisted"

Revision ID: bb53a1fe1696
Revises: e535ec00124a
Create Date: 2026-04-10 19:00:01.861023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb53a1fe1696'
down_revision: Union[str, None] = 'e535ec00124a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'theme')
    # ### end Alembic commands ###
